const jokes = [
    'Was hat vier Beine und kann fliegen? Zwei Vögel.',
    'Ich habe mir endlich so eine Dachbox für das Auto geholt. Echt praktisch muss ich sagen. Die Kinder hört man kaum noch.',
    'Ich hatte einen Traum, dass ich ein riesiges Brötchen aß. Als ich aufwachte war mein Kissen weck.',
    'Warum haben Giraffen so einen langen Hals? Weil der Kopf so weit oben ist.',
    'Was ist schwarz und klebt an der Decke? Ein schlechter Elektriker.',
    'Fliegt ein Kuckuck über den Atlantik, taucht ein Hai unter ihm auf. Sagt der Kuckuck: "Hai". Sagt der Hai: "Kuckuck".',
    'Was ist grün und wird auf Knopfdruck rot? Ein Frosch im Mixer.',
    'Ich konnte es nicht fassen. Mein Nachbar hat tatsächlich noch um 3 Uhr Nachts bei uns geklingelt. Mir wäre fast die Bohrmaschine runtergefallen.',
    'Ein Beamter zum anderen: "Ich weiß gar nicht, was die Leute gegen uns haben, wir tun doch nichts.',
    'Windows ist wie ein U-Boot,sobalt man ein Fenster öffnet,fangen die Probleme an.',
    'Ich bin heute aus dem Töpferkurs geflogen. Habe mich wohl im Ton vergriffen.',
    'Warum können Geister so schlecht lügen? – Weil sie so leicht zu durchschauen sind.',
    'Warum summen Bienen? Weil sie den Text nicht können.',
    'Was sitzt auf einem Baum und schreit "Aha"? Ein Uhu mit Sprachfehler.',
    'Was machen zwei wütende Schafe? Sie kriegen sich in die Wolle.',
    'Wo findet man viele Kühe? In einem Muuuuseum.',
    'Wie nennt man einen Bumerang der nicht zurück kommt? Einen Stock.',
    'Meine Arbeitsplatz ist sicher. Niemand will ihn.',
    'Gestern noch stand ich am Rand eines Abgrunds. Heute bin ich einen Schritt weiter.',
    'Wenn Chuck Norris mit nassen Fingern an der Steckdose rumfummelt, kriegt das Kraftwerk einen Schlag.',
    'Chuck Norris war bereits auf dem Mars. Das ist der Grund dafür, warum es dort kein Leben mehr gibt.',
    'Chuck Norris wurde letztens von der Polizei angehalten. Die Polizisten sind mit einer Verwarnung davon gekommen.',
    'Wenn Chuck Norris ein Ei essen möchte, pellt er das Huhn.',
    'Chuck Norris isst keinen Honig, er kaut Bienen.',
    'Einmal hat Chuck Norris eine ganze Torte gegessen, bevor ihm jemand sagen konnte, dass eine Stripperin drin war.',
    'Chuck Norris darf bei Ikea auch die gelbe Tasche mitnehmen.',
    'Chuck Norris ist Fallschirmspringen gegangen. Sein Fallschirm hat sich nicht geöffnet. Er ist den Fallschirm danach umtauschen gegangen.',
    'Chuck Norris geht jeden Monat Blut spenden, nur nicht sein eigenes.',
    'Als Chuck Norris sein Elternhaus verließ, sagt er zu seinem Vater: "So jetzt bist du der Mann im Haus.".',
    'Chuck Norris kann im Kinderkarussell überholen.',
    'Die Cowboystiefel von Chuck Norris sind aus echten Cowboys.',
    'Chuck Norris hat als Kind Sandburgen gebaut. Heute nennt man sie Pyramiden.',
    'Wie nennt man ein helles Mammut? Hellmut.',
    'Warum ging der Luftballon kaputt? – Aus Platzgründen.',
    'Ich habe dem Typ vor Dir einen Limonaden-Witz erzählt. Fanta lustig.',
    'Ich hab letztens einen Chemiewitz erzählt. - Gab keine Reaktion.',
    'Was ist ein Ritter im Kannibalendorf? Dosenfutter.',
    'Was passiert wenn man Cola und Bier gleichzeitig trinkt? Man kolabiert.',
    'Was findet man beim Kannibalen in der Dusche? Head and Shoulders.',
    'Was essen Autos am liebsten? Park Plätzchen.',
    'Warum trinken Mäuse keinen Alkohol? Weil sie Angst vorm Kater haben.',
    'Was entsteht, wenn sich ein Igel und ein Regenwurm paaren? Eine Rolle Stacheldraht.',
    'Unterhalten sich zwei Eiszapfen. Sagt der eine zum anderen: "Hey, kannste mir mal Geld leihen?" Darauf der andere: "Ne, sorry! Bin momentan nicht flüssig."',
    'Ich habe einem Hipster ans Bein getreten. Jetzt hopster.',
    'Was sitzt auf dem Baum und winkt? ... Ein Huhu.',
    'Wer ist der größte Schummler im Dschungel? ... Mogli.',
    'Wissenschaftler haben herausgefunden. Und sind dann wieder reingegangen.',
    'Was isst der Dalai Lama zum Frühstück? ... Ein Buddhabrot.',
    'Was braucht ein Blinder im Schwimmbad? ... Einen Sehhund.',
    'Wie viele Liegestütze schafft Chuck Norris? ... Alle.',
    'Warum gehen Ameisen nicht in die Kirche? ... Weil sie in Sekten sind.',
    'Chuck Norris liest keine Bücher: Er starrt sie so lange an, bis sie ihm freiwillig sagen, was er wissen will.',
    'Chuck Norris putzt keine Zähne, die Zähne putzen Chuck Norris.',
    'Chuck Norris strickt gern Pullover in seiner Freizeit, und wenn ich "strickt" sage, meine ich kickt und mit "Pullover" meine ich Menschen.',
    'Es gibt keine Evolution, sondern nur eine Liste von Kreaturen, denen Chuck Norris erlaubt zu leben.',
    'Chuck Norris war der Auslöser für den Urknall.',
    'Chuck Norris glaubt nicht an Gott. Gott glaubt an Chuck Norris.',
    'Chuck Norris trägt keine Uhr. Er entscheidet wie spät es ist.',
    "Als Kind hat Chuck Norris nie für Geschichte gelernt. Die Geschichte hat sich nach Klassenarbeiten an Chuck's Antworten angepasst.",
    'Chuck Norris reitet nicht. Er ist schneller ohne Pferd.',
    'Chuck Norris kann schneller stehen als du rennen kannst.',
    'Was ist gelb und hüpft durch den Wald? — Der Postfrosch.',
    'Sagt der Pessimist „Schlimmer geht nicht!“ — Sagt der Optimist: „Doch.“',
    'Geht ein Neutron in eine Disco. Sagt der Türsteher: Hier kommen heute nur geladene Gäste rein.',
    'Was ist schwarz-weiß gestreift und kommt nicht vom Fleck? Ein Klebra.',
    'Chuck Norris schmiss neulich eine Party. 100 Meter weit.',
    'Chuck Norris nimmt bei einem 100 Meter Sprint eine Abkürzung.',
    'Geht ein Pferd in eine Bar, fragt der Barkeeper: Wieso so ein langes Gesicht?',
    'Chuck Norris ist gestern gestorben. Heute geht es ihm aber schon wieder besser.',
    'Gott sagte, "Es werde Licht". Chuck Norris antwortete "Sag Bitte."',
    'Chuck Norris bekommt 20% Rabatt bei Praktiker. Auch auf Tiernahrung.',
    'Chuck Norris isst sein Knoppas schon um 9.',
    'Ich bin nicht schizophren. Ich auch nicht.',
    'Wenn ein Professor ein Sandwich macht, ist es dann wissenschaftlich belegt?',
    'Meine Freundin meint ich sei neugierig. Zumindestens steht das in ihrem Tagebuch.',
    'Was kommt nach Elch? Ist doch klar. Zwölch.',
    'Was sind die teuersten Tomaten? Na? Die Geldautomaten.',
    'Wie nennt man einen Bären, der auf einer Kugel sitzt und schreit? Einen Kugelschrei Bär',
    'Ich versuchte gestern beim Flughafen B E R anzurufen. Da hebt aber niemand ab.',
    'Was fliegt durch die Luft und macht Muß Muß? Eine Biene im Rückwärtsgang!',
    'Was machen Tiere in der Disko? Na sie Diskotieren.',
    'Welche Sprache spricht man in der Sauna? Na ist doch klar. Schwitzerdeutsch.',
    'Wie betrinkt sich eine Mücke? Insekt.',
    'Wo geht ein Wahl zum Mittagessen? Ins Wahllokal.',
    'Was macht ein Clown im Büro? Faxen.',
    'Was heißt Sonnenuntergang auf Finnisch? Helsinki.',
    'Warum sieht man in Kirchen keine Ameisen? Weil sie in Sekten sind',
    'Was ist grün und steht vor der Tür? Ein Klopfsalat.',
    'Was sagt ein Krokodil, das einen Clown gefressen hat? Schmeckt irgendwie komisch.',
    'Was liegt am Strand und redet undeutlich? Eine Nuschel.',
    'Was ist rot und hat drei Ecken? Ein rotes Dreieck.',
    'Geht ein Arzt zum Mann. Fragt der Mann: Müsste es nicht umgekehrt sein?',
    'Was ist gelb und kann nicht schwimmen? Ein Schaufelbagger.',
    'Ich habe neulich einen Geisterfahrer getroffen. Der war sehr entgegenkommend.',
    'Was ist grau und kann nicht fliegen? Ein Parkplatz.',
    'Was ist schwarz, weiß und schaukelt? Ein Schwinguin.',
    'Wie nennt man einen Esel auf einem Berg? Einen Esel.',
    'Chuck Norris trinkt seinen Kaffee schwarz. Ohne Wasser.',
    'Ich habe Redbull mit Kaffee gemischt. Jetzt kann ich Geräusche sehen.',
    'Chuck Norris trinkt keinen Kaffee, er zerkaut die Bohnen.'
]

function getRandomNumber (array) {
    const randomNumber = Math.floor((Math.random() * array.length))
    return randomNumber
}

function getRandomJoke () {
    return jokes[getRandomNumber(jokes)]
}

module.exports = {
    getRandomJoke
}